### ISSUE TITLE
Undefined names: CUDA, CylinderGridGenFunction

### ISSUE THREAD

**Issue by cclauss** [roytseng-tw/mask-rcnn.pytorch#5]
flake8 testing of https://github.com/roytseng-tw/mask-rcnn.pytorch on Python 3.6

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./lib/setup.py:93:48: F821 undefined name 'CUDA'
            self.set_executable('compiler_so', CUDA['nvcc'])
                                               ^
./lib/model/roi_crop/modules/gridgen.py:39:18: F821 undefined name 'CylinderGridGenFunction'
        self.f = CylinderGridGenFunction(self.height, self.width, lr=lr)
                 ^
2     F821 undefined name 'CylinderGridGenFunction'
2
```

**Comment by roytseng-tw** [comment]
1. For  `./lib/setup.py:93:48: F821 undefined name 'CUDA'`:
The injection code seems to come from [py-faster-rcnn's setup.py](https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/setup.py) for compiling gpu nms. However, it's not needed anymore. So I remove the relating code for `custom_build_ext`.

2. `undefined name 'CylinderGridGenFunction'`
Yes, `CylinderGridGenFunction` is missing and I don't know where does the implementation of roi_crop originally comes from (I coppied the code from https://github.com/jwyang/faster-rcnn.pytorch). Fortunately, `CylinderGridGen` is never used, so I just comment out the lines for now. 

Fixed in 9efdd0550fde075688e7b8bc805370dccf1a7dc5.
